---
title: "Text Clustering"
author: "Ayoub Bagheri"
date: "6/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Medical Text Clustering

Ref: https://cran.r-project.org/web/packages/textmineR/vignettes/b_document_clustering.html

```{r clustering}
library(textmineR)

# load nih_sample data set from textmineR
data(nih_sample)

# create a document term matrix 
dtm <- CreateDtm(doc_vec = nih_sample$ABSTRACT_TEXT, # character vector of documents
                 doc_names = nih_sample$APPLICATION_ID, # document names
                 ngram_window = c(1, 2), # minimum and maximum n-gram length
                 stopword_vec = c(stopwords::stopwords("en"), # stopwords from tm
                                  stopwords::stopwords(source = "smart")), # this is the default value
                 lower = TRUE, # lowercase - this is the default value
                 remove_punctuation = TRUE, # punctuation - this is the default
                 remove_numbers = TRUE, # numbers - this is the default
                 verbose = FALSE, # Turn off status bar for this demo
                 cpus = 2) # default is all available cpus on the system

# construct the matrix of term counts to get the IDF vector
tf_mat <- TermDocFreq(dtm)

```


```{r}
# TF-IDF and cosine similarity
tfidf <- t(dtm[ , tf_mat$term ]) * tf_mat$idf

tfidf <- t(tfidf)

csim <- tfidf / sqrt(rowSums(tfidf * tfidf))

csim <- csim %*% t(csim)

cdist <- as.dist(1 - csim)

```


```{r}
hc <- hclust(cdist, "ward.D")

clustering <- cutree(hc, 10)

plot(hc, main = "Hierarchical clustering of 100 NIH grant abstracts",
     ylab = "", xlab = "", yaxt = "n")

rect.hclust(hc, 10, border = "red")
```

```{r}
p_words <- colSums(dtm) / sum(dtm)

cluster_words <- lapply(unique(clustering), function(x){
  rows <- dtm[ clustering == x , ]
  
  # for memory's sake, drop all words that don't appear in the cluster
  rows <- rows[ , colSums(rows) > 0 ]
  
  colSums(rows) / sum(rows) - p_words[ colnames(rows) ]
})
```


```{r}
# create a summary table of the top 5 words defining each cluster
cluster_summary <- data.frame(cluster = unique(clustering),
                              size = as.numeric(table(clustering)),
                              top_words = sapply(cluster_words, function(d){
                                paste(
                                  names(d)[ order(d, decreasing = TRUE) ][ 1:5 ], 
                                  collapse = ", ")
                              }),
                              stringsAsFactors = FALSE)

cluster_summary
```

```{r}
# plot a word cloud of one cluster as an example
wordcloud::wordcloud(words = names(cluster_words[[ 5 ]]), 
                     freq = cluster_words[[ 5 ]], 
                     max.words = 50, 
                     random.order = FALSE, 
                     colors = c("red", "yellow", "blue"),
                     main = "Top words in cluster 100")
```

```{r}
library(ggdendro)
library(tidyverse)
library(dendextend)
# Compute 2 hierarchical clusterings
hclust_mod1 <- hclust(cdist, method = "complete")
hclust_mod2 <- hclust(cdist, method = "average")
ggdendrogram(hclust_mod1) + labs(title="Complete-linkage Hierarchical clustering")
ggdendrogram(hclust_mod2) + labs(title="Average-linkage Hierarchical clustering")


```

```{r}
cut_avg <- cutree(hclust_mod1, k = 3)
plot(hclust_mod1)
rect.hclust(hclust_mod1 , k = 3, border = 2:6)
abline(h = 3, col = 'red')
```


```{r}
avg_dend_obj <- as.dendrogram(hclust_mod2)
avg_col_dend <- color_branches(avg_dend_obj, h = 100)
plot(avg_col_dend)
```


```{r}
# Create two dendrograms
dend1 <- as.dendrogram (factor(cutree(hclust_mod1, k = 3)))
dend2 <- as.dendrogram (factor(cutree(hclust_mod2, k = 3)))

# Create a list to hold dendrograms
dend_list <- dendlist(dend1, dend2)

# Align and plot two dendrograms side by side
dend_list %>%
  untangle(method = "step1side") %>% # Find the best alignment layout
  tanglegram()                       # Draw the two dendrograms
```

```{r}
# first, let's make two factors with congruent labels for the observations
hclust_fac <- factor(cutree(hclust_mod1, k = 3), labels = c("a", "b", "c"))
kmeans_fac <- factor(cutree(hclust_mod2, k = 3), labels = c("b", "c", "a"))

# then we can check whether the labels are the same
same_clust <- hclust_fac == kmeans_fac
all(same_clust)
sum(!same_clust)

```

